version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: healthtrackr
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  postgres:
    image: postgres:latest
    container_name: postgres
    network_mode: bridge
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - psql-data:/var/lib/postgresql/data
       
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    network_mode: bridge
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  

volumes:
  psql-data:
  pgadmin-data: